import React from "react"
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import Header from "../components/header"
import Logo from "../Images/Logo.png"
import SearchIcon from '@material-ui/icons/Search';
import axios from "axios"
import { useState, useEffect } from 'react'
import { Button } from '@material-ui/core';
import AffiliateProducts from '../components/AffiliateProducts'
import Footer from '../components/Footer'
import Search from "../components/search"
import CloseIcon from '@mui/icons-material/Close';
import Script from 'next/script'
import AffiliateProductSlider from "../components/AffiliateProductSlider"


export default function Home() {
  const [posts, setPosts] = useState([])
  const [search, setSearch] = useState(false)

  var aax_size = '300x250';
  var aax_pubname = 'bharatjangir1-21';
  var aax_src = '302'

  useEffect(() => {
    const getPosts = async () => {
      const posts = await axios.get("/api/post")
      const post = posts.data
      setPosts(post.reverse())
    }

    getPosts()
  }, [])


  const date = (date) => {
    var _date = date.split("-" && "T")
    return _date[0]
  }

  console.log(posts[5]);
  return (

    <div className={styles.Home_Container}>
      <Head>
        <title>Story Teller</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut  icon" type="image/png" href="frontend/storyteller/Images/Logo.png" />
      </Head>
      <Header />
      <div>
        <AffiliateProductSlider/>
      </div>
      <div className={styles.Home_Container_SearchBar}>
        <div className={styles.Home_Container_SearchBar_content}>
          <input type="text" className={styles.SearchInput} placeholder="Search" onClick={() => setSearch(true)} />
          <SearchIcon className={styles.searchIcon} />
        </div>
      </div>
      <div className={styles.Content_container}>
        <div className={styles.Home_Container_HindiStories}>
          <div className={styles.Home_Container_HindiStories_heading}>
            <h1>हिंदी कहानियाँ</h1>
          </div>
          <div className={styles.Allposts_or_contents}>
            {
              posts.slice(0, 6).map(data => {
                if (data.language === "Hindi")
                  return (
                    <Link href={`/post/${data._id}`} key={data._id}>
                      <div className={styles.HindiStories_Content}>
                        <div className={styles.Content_heading}>
                          <h1>{data.heading}</h1>
                        </div>
                        <div className={styles.Content_subheading}>
                          <h2>
                            {data.subheading}
                          </h2>
                        </div>
                        {/* <div className={styles.Content_content}>
                          <pre>
                            {data.content[0].content}
                          </pre>
                        </div> */}
                        <div className={styles.Content_date}>
                          <p>
                            Published At:
                            {date(data.createdAt)}
                          </p>
                        </div>
                      </div>
                    </Link>


                  )
              })
            }
          </div>
          <div className={styles.Seemore_btn}>
            <Link href="/hindistories">
              <Button variant="contained" >सभी देखें</Button>
            </Link>
          </div>
        </div>

        <div className={styles.Home_Container_HindiStories}>
          <div className={styles.Home_Container_HindiStories_heading}>
            <h1>English Stories</h1>
          </div>
          <div className={styles.Allposts_or_contents}>
            {
              posts.slice(0, 6).map(data => {
                if (data.language === "English")
                  return (
                    <Link href={`/post/${data._id}`} key={data._id}>
                      <div className={styles.HindiStories_Content} key={data._id}>
                        <div className={styles.Content_heading}>
                          <h1>{data.heading}</h1>
                        </div>
                        <div className={styles.Content_subheading}>
                          <h2>
                            {data.subheading}
                          </h2>
                        </div>
                        {/* <div className={styles.Content_content}>
                          <pre>
                            {data.content}
                          </pre>
                        </div> */}
                        <div className={styles.Content_date}>
                          <p>
                            Published At:
                            {date(data.createdAt)}
                          </p>
                        </div>
                      </div>
                    </Link>


                  )
              })
            }
          </div>
          <div className={styles.Seemore_btn}>
            <Link href="/englishstories">
              <Button variant="contained">See More</Button>
            </Link>
          </div>
        </div>

      </div>

      <AffiliateProducts />
      <Footer />
      {
        search &&
        <div className={styles.SearchItems_Component_container}>
          <CloseIcon onClick={() => setSearch(false)} style={{ color: "red", position: "absolute" }} />
          <Search />
        </div>

      }

    </div>
  )
}
